// flow-typed signature: 644dea5f0efc7e4890502edff2a93269
// flow-typed version: <<STUB>>/customize-cra_v^0.5.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'customize-cra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'customize-cra' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'customize-cra/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'customize-cra/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'customize-cra/dist/index.cjs.js' {
  declare module.exports: $Exports<'customize-cra/dist/index.cjs'>;
}
declare module 'customize-cra/dist/index.esm.js' {
  declare module.exports: $Exports<'customize-cra/dist/index.esm'>;
}
