// flow-typed signature: 99287cc5618b2f873094d449379d8f95
// flow-typed version: <<STUB>>/jest-axe_v^3.2.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-axe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-axe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-axe/extend-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-axe/extend-expect.js' {
  declare module.exports: $Exports<'jest-axe/extend-expect'>;
}
declare module 'jest-axe/index' {
  declare module.exports: $Exports<'jest-axe'>;
}
declare module 'jest-axe/index.js' {
  declare module.exports: $Exports<'jest-axe'>;
}
