// flow-typed signature: f2174cd7e36366e2123100fffd7716b1
// flow-typed version: <<STUB>>/react-error-boundaries_v^1.1.4/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-error-boundaries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-error-boundaries' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-error-boundaries/dist/commonjs/Fallback' {
  declare module.exports: any;
}

declare module 'react-error-boundaries/dist/commonjs' {
  declare module.exports: any;
}

declare module 'react-error-boundaries/dist/commonjs/Modal' {
  declare module.exports: any;
}

declare module 'react-error-boundaries/dist/commonjs/WithErrorHandler' {
  declare module.exports: any;
}

declare module 'react-error-boundaries/dist/es/Fallback' {
  declare module.exports: any;
}

declare module 'react-error-boundaries/dist/es' {
  declare module.exports: any;
}

declare module 'react-error-boundaries/dist/es/Modal' {
  declare module.exports: any;
}

declare module 'react-error-boundaries/dist/es/WithErrorHandler' {
  declare module.exports: any;
}

declare module 'react-error-boundaries/dist/umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-error-boundaries/dist/commonjs/Fallback.js' {
  declare module.exports: $Exports<'react-error-boundaries/dist/commonjs/Fallback'>;
}
declare module 'react-error-boundaries/dist/commonjs/index' {
  declare module.exports: $Exports<'react-error-boundaries/dist/commonjs'>;
}
declare module 'react-error-boundaries/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-error-boundaries/dist/commonjs'>;
}
declare module 'react-error-boundaries/dist/commonjs/Modal.js' {
  declare module.exports: $Exports<'react-error-boundaries/dist/commonjs/Modal'>;
}
declare module 'react-error-boundaries/dist/commonjs/WithErrorHandler.js' {
  declare module.exports: $Exports<'react-error-boundaries/dist/commonjs/WithErrorHandler'>;
}
declare module 'react-error-boundaries/dist/es/Fallback.js' {
  declare module.exports: $Exports<'react-error-boundaries/dist/es/Fallback'>;
}
declare module 'react-error-boundaries/dist/es/index' {
  declare module.exports: $Exports<'react-error-boundaries/dist/es'>;
}
declare module 'react-error-boundaries/dist/es/index.js' {
  declare module.exports: $Exports<'react-error-boundaries/dist/es'>;
}
declare module 'react-error-boundaries/dist/es/Modal.js' {
  declare module.exports: $Exports<'react-error-boundaries/dist/es/Modal'>;
}
declare module 'react-error-boundaries/dist/es/WithErrorHandler.js' {
  declare module.exports: $Exports<'react-error-boundaries/dist/es/WithErrorHandler'>;
}
declare module 'react-error-boundaries/dist/umd/index' {
  declare module.exports: $Exports<'react-error-boundaries/dist/umd'>;
}
declare module 'react-error-boundaries/dist/umd/index.js' {
  declare module.exports: $Exports<'react-error-boundaries/dist/umd'>;
}
