// flow-typed signature: 90a9acaea462f1fd28d3d936d4310f8a
// flow-typed version: <<STUB>>/swr_v^0.1.12/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swr/dist' {
  declare module.exports: any;
}

declare module 'swr/esm/config' {
  declare module.exports: any;
}

declare module 'swr/esm' {
  declare module.exports: any;
}

declare module 'swr/esm/libs/hash' {
  declare module.exports: any;
}

declare module 'swr/esm/libs/is-document-visible' {
  declare module.exports: any;
}

declare module 'swr/esm/libs/is-online' {
  declare module.exports: any;
}

declare module 'swr/esm/libs/throttle' {
  declare module.exports: any;
}

declare module 'swr/esm/libs/use-hydration' {
  declare module.exports: any;
}

declare module 'swr/esm/swr-config-context' {
  declare module.exports: any;
}

declare module 'swr/esm/types' {
  declare module.exports: any;
}

declare module 'swr/esm/use-swr-pages' {
  declare module.exports: any;
}

declare module 'swr/esm/use-swr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swr/dist/index' {
  declare module.exports: $Exports<'swr/dist'>;
}
declare module 'swr/dist/index.js' {
  declare module.exports: $Exports<'swr/dist'>;
}
declare module 'swr/esm/config.js' {
  declare module.exports: $Exports<'swr/esm/config'>;
}
declare module 'swr/esm/index' {
  declare module.exports: $Exports<'swr/esm'>;
}
declare module 'swr/esm/index.js' {
  declare module.exports: $Exports<'swr/esm'>;
}
declare module 'swr/esm/libs/hash.js' {
  declare module.exports: $Exports<'swr/esm/libs/hash'>;
}
declare module 'swr/esm/libs/is-document-visible.js' {
  declare module.exports: $Exports<'swr/esm/libs/is-document-visible'>;
}
declare module 'swr/esm/libs/is-online.js' {
  declare module.exports: $Exports<'swr/esm/libs/is-online'>;
}
declare module 'swr/esm/libs/throttle.js' {
  declare module.exports: $Exports<'swr/esm/libs/throttle'>;
}
declare module 'swr/esm/libs/use-hydration.js' {
  declare module.exports: $Exports<'swr/esm/libs/use-hydration'>;
}
declare module 'swr/esm/swr-config-context.js' {
  declare module.exports: $Exports<'swr/esm/swr-config-context'>;
}
declare module 'swr/esm/types.js' {
  declare module.exports: $Exports<'swr/esm/types'>;
}
declare module 'swr/esm/use-swr-pages.js' {
  declare module.exports: $Exports<'swr/esm/use-swr-pages'>;
}
declare module 'swr/esm/use-swr.js' {
  declare module.exports: $Exports<'swr/esm/use-swr'>;
}
