version: "3.7"

services:
  web-django:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.web
      target: django
    image: ooux/tmp-django

  web-react:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.web
      target: react
    image: ooux/tmp-react

  web-server:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.web
      target: nginx
    image: ooux/nginx
